// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC66sI4vpsMxiOAfWlGVRNoxBcVAaq4EG4',
    appId: '1:522777027371:web:ceb4a3439df33bc5a2db6e',
    messagingSenderId: '522777027371',
    projectId: 'profileapp-de8e6',
    authDomain: 'profileapp-de8e6.firebaseapp.com',
    storageBucket: 'profileapp-de8e6.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStAHksnUioMQr3luLvS3RRcCrXWFOgd8',
    appId: '1:522777027371:android:80ae299fc0640639a2db6e',
    messagingSenderId: '522777027371',
    projectId: 'profileapp-de8e6',
    storageBucket: 'profileapp-de8e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuGOWtiiCCgRTRdIebsDzBP0Tt_RxS5uQ',
    appId: '1:522777027371:ios:d744a92ca70a3f0da2db6e',
    messagingSenderId: '522777027371',
    projectId: 'profileapp-de8e6',
    storageBucket: 'profileapp-de8e6.appspot.com',
    iosClientId: '522777027371-d2di54g6t79ifpc9m5b1kvosdtaktr8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.profileApp',
  );
}
